# Generated by Django 4.2.15 on 2024-08-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_userdata_payment_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="blocked_for_tasker",
            field=models.BooleanField(default=False),
        ),
    ]
