# Generated by Django 4.2.17 on 2024-12-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_userdata_blocked_for_tasker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="profile_pic",
            field=models.URLField(blank=True, null=True, verbose_name="Profile Photo"),
        ),
    ]
