# Generated by Django 4.2.17 on 2024-12-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(
                blank=True, max_length=180, null=True, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(
                blank=True, max_length=100, null=True, unique=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_photo",
            field=models.URLField(blank=True, null=True, verbose_name="Profile Photo"),
        ),
    ]
