# Generated by Django 4.2.17 on 2024-12-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_address_alter_profile_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.CharField(default="Unknown", max_length=250),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(
                default="Unknown City", max_length=180, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(
                default="email", max_length=100, unique=True, verbose_name="Email"
            ),
        ),
    ]
