# Generated by Django 5.0.4 on 2024-08-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_chat_receiver_alter_chat_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
