# Generated by Django 5.0.4 on 2024-08-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_alter_appointment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="otp_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
