# Generated by Django 5.0.4 on 2024-07-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_workers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasker",
            name="subscribed",
            field=models.BooleanField(default=True),
        ),
    ]
