# Generated by Django 5.0.4 on 2024-07-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_workers", "0002_tasker_subscribed"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subscription_type",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name="tasker",
            name="subscription_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tasker",
            name="subscription_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tasker",
            name="subscription_type",
            field=models.CharField(
                choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                default="monthly",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="tasker",
            name="subscribed",
            field=models.BooleanField(default=False),
        ),
    ]
