# Generated by Django 5.0.4 on 2024-08-02 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_workers", "0004_tasker_admin_approval"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasker",
            name="rating",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
