# Generated by Django 4.2.17 on 2024-12-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_workers", "0007_remove_tasker_subscription_plan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasker",
            name="work_photo",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="Work Photo URL"
            ),
        ),
        migrations.AlterField(
            model_name="workcategory",
            name="work_image",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="Work Image URL"
            ),
        ),
    ]
